#ifdef BUILD_STRINGS
const char* messages[] = {
_("Original Theme"),
// stones
_("Empty Stone"),
_("1 Skull"),
_("2 Skulls"),
_("3 Skulls"),
_("4 Skulls"),
_("5 Skulls"),
_("6 Skulls"),
_("7 Skulls"),
_("8 Skulls"),
_("9 Skulls"),
_("1 Sword"),
_("2 Swords"),
_("3 Swords"),
_("4 Swords"),
_("5 Swords"),
_("6 Swords"),
_("7 Swords"),
_("8 Swords"),
_("9 Swords"),
_("1 Number"),
_("2 Numbers"),
_("3 Numbers"),
_("4 Numbers"),
_("5 Numbers"),
_("6 Numbers"),
_("7 Numbers"),
_("8 Numbers"),
_("9 Numbers"),
_("East Wind"),
_("South Wind"),
_("West Wind"),
_("Nord Wind"),
_("White Dragon"),
_("Green Dragon"),
_("Red Dragon"),
// winds
_("East"),
_("South"),
_("West"),
_("North"),
// clans
_("Maitha"),
_("Kartha"),
_("Iz"),
_("Marz"),
// creatures
_("Skeleton Horde"),
_("Shadow"),
_("Durlock"),
_("Wraith"),
_("Maz'Ra"),
_("Knight Templar"),
_("Minotaur"),
_("Adventure Party"),
_("Fire Giant"),
_("Sand Wraith"),
_("Stone Golem"),
_("Thunder Bird"),
_("Ki-Lin"),
_("Tornado"),
_("Griffon"),
_("Chameleon"),
_("Kilor Celsbane"),
_("Carol the Great"),
_("King Drago"),
_("Learra the Siren"),
_("Shanahan"),
_("White Dragon"),
_("Green Dragon"),
_("Red Dragon"),
_("Fire Elemental"),
_("Earth Elemental"),
_("Air Elemental"),
_("Water Elemental"),
_("Juggernaut"),
// spells
_("Smoke"),
_("Demonic Compulsion"),
_("Mass Panic"),
_("Paralyze"),
_("Reduction"),
_("Battle Fury"),
_("Guidance"),
_("Force Shield"),
_("Dust Cloud"),
_("Heroism"),
_("Mystical Fountain"),
_("Blind Ambition"),
_("Brilliant Lights"),
_("Magical Aura"),
_("Teleport"),
_("Dispel Magic"),
_("Lightning Bolt"),
_("Healing"),
_("Hell Blast"),
_("Summon Skull Rune"),
_("Summon Sword Rune"),
_("Summon Number Rune"),
_("Random Discard"),
_("Scry Runes"),
_("Silence"),
_("Mana Fog"),
_("Mass Dispel Magic"),
// persons
_("Orachi"),
_("Lakkho"),
_("Dayla"),
_("Ziag"),
_("Niana"),
_("Kierac"),
_("Logun"),
_("Nucrus"),
_("Javed"),
// person ability
_("%1's monacle allows him to see all invisible units on the map."),
_("%1's catasrophic Hellblast can wipe out entire army lines and is unique to her."),
_("Being a bard, %1 is loved by all people and creatures around him. His songs inspire bravery which cause his creatures to regain 2 loyalty each round."),
_("%1 posesses unmatched skill and seemingly endless luck in the Rune Game. For this reason he always seems to draw the runes he needs."),
_("%1 is a telepath. This allows him to chose, pung, kong, game and cast spells even when silence has been cast."),
// person dignity
_("Lord of the Dead"),
_("High Lord Templar"),
_("Sea Princess"),
_("The Tactician"),
_("Enchantress of Fire"),
_("The Shapeshifter"),
_("Minstrel of Magic"),
_("The Trickster"),
_("Master of the Skies"),
// person description
_("\tThe spawn of all that is evil and callous is the necromancer called %1. The Isle of Four winds knows no individual as ruthless as he, the one without emotion. Sadness, fear, anger, joy, jealousy and greed are sensations that do not clutter his being, making him the most focused and feared of all wizards. Death and decay are all that are required to fuel his existence, they are his conscience. His aspect is a composition of energy from this arcane persuasion. When looking into his shadowy eyes you can almost see the tortured souls of those who have crossed his path. It is said that when you meet %1, you have met death.\
\n\tThe nature of %1's existence revolves around the magic that is found within the realm of skulls. He is singularly in tune with death as a source of magical essence. It is the fabric of his being. %1's unearthly aura pulsates with the dark fire of death. This has become his only link to the Isle of the Four Winds and for this reason %1 is limited to the use of Skull magic as his source of summoning and enchantment. However, due to his proximity to death, %1 is also attuned to the most destructive creatures found on the Isle. He has managed to call upon the Red Dragon, the Fire Elemental, and Maz'Ra the Demon Lord to do his bidding, and will not hesitate to call on them throughout the next competition.\
\n\t%1 is a true mercenary, not native to any of the races which vie for control of the Isle of Four Winds. He will choose to side with races only to suit his own needs, and to fortify his intensely evil magical essence. The Maitha and the Marz are the only communities brave enough to have managed to secure the use of %1 as an instrument in past Rune Wars. %1 will again side with one of these two clans in hopes to achieve total dominance and escalate his diabolic vitality.\
\n\t%1 is somewhat of an unknown. Although he is very much alive, considerable folklore has been attached to his movements. Natives to all the races on the Isle have cited many reasons for his existence and continue to speculate. Some say that he is an overlord to rival the Gods through constant killing sprees.His wanderings across the countryside have left it dark and destitute. Others believe that he is an incarnation of all that is evil. What is agreed upon is that %1 is most certainly the most bizarre and most fearsome individual on the island. If a wizard is to defeat him in the coming competition, he or she will have to have an iron will and a heart of stone, for %1 does not let up."),
_("\t%1 of the Kartha stands by the chivalric code of the honorable knight. All that he accomplishes or attempts is for the good of his nation. His piety and conviction to his people is unmatched by any other figure throughout the land. %1 truly believes that there is much to be gained through patience and virtue. His commitment to ethics is not a byproduct of his religious beliefs, moreover, it comes from within his magical fabric. %1's dedication and perseverance has allowed him to harvest his magical aura and detach himself from a mundane existence. This separates him from mere ordinary knights or crusaders of a church. The magic he possesses has become an extension of his blade, and it flourishes within him as hones his skills as a master swordsman and conjurer of good.\
\n\tThe intense studies of the Knighthood have allowed %1 to discover a greater understanding of the magic that lies deep within his soul. His patience has become instinct as in the case of most Kartha clansfolk, however, %1 has most certainly fortified this attribute through his machine-like conviction. His magical nature lies within the power of the sword, therefore all that is summoned and enchanted by %1 is attached to this realm. Quite often, %1 is seen conjuring the aid of reputable heroes like Carol the Great and King Drago. He especially enjoys the company of these individuals because they share the sanctity that he so desperately cherishes. %1 finds strength in his summonings, and for this reason, is rarely seen alone.\
\n\t%1 is misunderstood by the other races native to the Isle of Four Winds. He is often considered a soft hearted individual willing to take pity on those that are deemed to be less fortunate. This, however, is the wrong angle to take when facing him in competition. While other wizards may expect him to limit the prize of his victory, he will pursue utter dominance. His absolute dedication to his people has instilled in him the will to claim a landslide victory. He intends to lead his people to glory. His strength of mind coupled with his unparallel sense of patience will make him a worthy opponent in the coming Rune War."),
_("\tThere is a point in the development of a powerful wizard when a teacher realizes his pupil is truly gifted. %1, a disciple of Kierac, never attained this peak. Kierac recognized her potential early, and acknowledges her as a competent, if unspectacular wizard, never to be seen within the confines of the Mage Tower for a rune war though.\
\n\tNo one can pinpoint the moment when she became a legitimate contender within the marz wizard hierarchy to be their preferred rune war mage. Her best quality seems to be the fact that she is constantly underestimated. Her tactics and spells are unspectacular for the most part, but in the end she always delivers a very strong impression.\
\n\tBeing full blooded marz means that she is a dual breather, and fully amphibious. Being underwater gives her lots of freedom. The entire island is littered with channels and rivers so it is easy for her to get around quietly and secretly. Her stealth rivals that of Kierac himself, though this is a very little known fact."),
_("\tAccording to %1, conditions for his victory are extremely ripe. His clan has become somewhat negligible in the eyes the other races due to the failure of past leaders to achieve success in previous Rune Wars. %1 is extremely determined to surprise the other wizards at the next competition. He has learned from past failure and has cited self betterment as the only possible course of action that will undo what has been done to his sorry nation. %1 has traveled the four corners of the Isle in order to obtain delicate magical information to quench his thirst for victory. Most of his magical essence is by choice self taught, having decided not to take on a mentor because of the pathetic pool of past leaders and wizards. %1 is very much in touch with the tides of magic which wash within his soul. He has learned to tap the innate magical nature of his clansfolk. Through intense magical study, %1 has discovered a way to harness the magical energy of his peoples desires. He will use this as a flagship of power to exact revenge over all the nations which call him weak.\
\n\tThere is a distinct property of war which %1 holds in high regard which may make him a potent foe in the next Rune War competition. %1 is a tactical genius and through intense study, thought and magic, %1 has become a master of tactical application. %1 has trained himself to sort and apply strategy with calculating speed. He has repeated his training methods so often that it has become instinct for him to adapt to different scenarios effectively. %1 prides himself on lightning quick thought, and will definitely outclass his opponents in this area of cerebral battle. He is able to see all invisible creatures with his controversial monocle. As well, all of his creatures are invisible.\
\n\tThe nature of %1's magic is inherently versatile. Although the focus of his summoning is based in the realm of skulls, he utilizes all areas of tactical spell casting, enchanting his creatures with a full complement of supplemental spells. %1 is never seen hoarding or saving the power that may come his way during a competition. He is constantly expending his power attempting to bolster his army with the various spells he has at his command. %1 is a very flashy fighter who relies on speed and finesse rather than pure power. He does not allow himself to be overwhelmed or overmatched. His intense grasp of enchantment magic demonstrates this.\
\n\t%1's crusade for knowledge has certainly raised the hopes of his people. He can feel their excitement as the magical energies flow through his blood. %1's ability to harness the hopes of his nation will make him a match for all wizards, especially those who regard the Iz as nothing more than a petty annoyance."),
_("\t%1 is another foreigner to the Isle of Four Winds, a human. Her intense aversion to the forces of evil have attracted her to the Isle. She has been following the legacy of a certain wizard in hopes of one day facing this individual and banishing him from the land of the living. Orachi is the one, the source of the raging tempest that blows within her passionate soul. Relentless in her pursuit, %1 has finally pinpointed the whereabouts of her arch nemesis and feels that she is finally ready to face him. She will take on any commission in the coming Rune War just to oppose Orachi. Although she will meet the needs of the clan who calls her, she is set on another purpose. %1 wants revenge.\
\n\tLong ago, %1 was a very passive woman, living in a small town far away from the Isle of Four Winds. She pursued the study of magic half-heartedly because she did not have the resources available to truly harness such power. Her town was extremely mundane, a small farming reserve beside a great river which the townsfolk had built their lives around. %1 was content with her life, dedicated to her family and her town until one fateful day. The skies suddenly darkened as an intense storm rose up and shook the foundations of the town. Following the storm, an army of corpses and demons entered the town, killing and spreading its curse to everything. At the heart of the army was a tortured soul, a twisted man that did not show emotion, Orachi the Necromancer. The town was consumed within minutes and all that was once living had transformed into living dead. Orachi left as quickly as he came, leaving the small farming town in ruins. %1 managed to escape the torment by hiding in a small cave at the bank of the river. When the sun came out and the blue sky returned she went back to town. There was nothing left, even the chirping birds had been stolen by this heartless being. %1 broke into a frenzy, she shed all that was pure and dedicated herself to revenge. Her only course of action was to pursue the art of summoning and enchantment. She turned to the only source of magic known to her lands, the Demon Lord. She struck a pact with him. %1 gave him her soul and in return was granted the gift of knowledge. She loathed her decision but her anger cluttered her judgement, all she wanted was revenge. She had become reborn as a child of fire.\
\n\tIntense study and magical manipulation was %1's way. She nurtured the fire the Demon had planted within her. Through ritual meditation, %1 fed the fire of knowledge. What was once a small blaze was transformed into a hellblast capable of consuming entire armies. Because of her aversion to the skull magic of Orachi, the magic within her guided itself. It took on the form of the sword and the number. As a result of this, %1 has become a summoner and an enchanter of these two realms, and a potent force in the coming Rune War."),
_("\t\"The absolute master of summoning\" is a title that describes %1. He is thought to be the oldest wizard on the Isle of Four Winds because of his intense grasp of the main summoning circles. Great mystery surrounds %1 much the same as it does Orachi except that %1 has not achieved his notoriety through mass torment and destruction. Rather, %1 has attained fame through his ability to alter his appearance via personal genetic manipulation. It is virtually impossible to chart his past movements. Therefore, very little is known about the age and background of %1, all is left to speculation.\
\n\tMany tales echo the name %1. One tale in particular has been agreed upon by many scholars and natives alike. %1 has participated in several Rune War competitions for the Marz and Iz clans. %1 says he favors these groups because they are considered somewhat alien. Throughout past competitions %1 has baffled his opponents with his ability to summon powerful creatures from all the main realms of magic; skulls, swords, and numbers. By drawing various entities from each realm he can form a decidedly deadly force. This leaves many opposing wizards scratching their collective heads, wondering how he could have possibly mastered such summoning.\
\n\tIt has been proposed that %1 must have studied under the masters of each realm of summoning. But how did he do this? None of the masters have admitted to teaching him. It was then discovered that he was indeed a shapeshifter. From this discovery it has been assumed that the great masters taught him unknowingly.\
\n\t%1 could care less about the methods he uses to obtain knowledge. He will use anything at his disposal to achieve total mastery of summoning, and to bring victory to those who call for him to represent them in the Rune War.\
\n\t%1 has an unmatched thirst and capacity to learn the art of summoning, causing him to be unaligned. His one motivation in life is summoning. So long as there is knowledge to be gathered %1 will pursue it using any means. He has dedicated his life to acquiring all available summoning knowledge, and from this, has become the most celebrated Rune War wizard of all time. He does not waste time with what he calls trivial supplemental magic. He claims victory by employing absolute brute force, summoning the strongest, meanest creatures. Once again %1 has to be looked upon as the frontrunner in the coming Rune War competition. Perhaps he will not compete. Only time will tell."),
_("\tAlthough %1 is a new face on the Isle of Four Winds, his participation in the coming Rune War is much anticipated. Not resident to the isle, %1 is a distinct type of faerie, foreign to all the native races. %1 is similar to Nucrus in that he shares no affiliation to a magical realm. However, his summoning skills are extremely potent. %1 has come into favor of the dragons and can summon all types of these devastating creatures. He has also discovered the secret of the Juggernaut and will most certainly call upon it to wreak absolute mayhem.\
\n\t%1, a mercenary in the truest sense, will lend his service to any clan that wishes to have him. Parables of his incredible summoning power have circulated throughout the land causing him to be the target of much interest by all the clans. Being of the bardly persuasion, %1 traversed the Isle of Four Winds on a self promotional tour, entertaining natives with songs and poems boasting of his fantastic powers. People have fallen in love with this enchanted performer. He has become their choice in the coming Rune War thus increasing his marketability amongst clan leaders. %1 will have many options available to him when it comes time to decide who he wishes to represent. People of all types back this charismatic hero, which many clan leaders have recognized. He is a representative of the common folk, the one to share a drink and a laugh with. Because many of the other wizards are feared for their anomalies, %1 is particularly adored for his jovial and charismatic nature. He has gained the enthusiasm of the natives and intends to feed from this. The sign of a great performer is a large crowd.\
\n\tA drawback to %1 is his lack of a supplemental spell realm. This may or may not expose a weakness, depending on how the runes fall for %1. This brash and persuasive character need only to look towards the dragons as a source of victory. %1 will be one to watch for this reason alone."),
_("\tTouted as the elite Rune War contestant, %1 is a representative of the Maitha clan. A veteran of past competition, %1 is the purest student of the actual game itself. He relies heavily on his ability to play the game rather than the magic contained within the runes. %1 is somewhat of a utility summoner and spell caster, only able to call upon the elements and minor beings to aid him in the battle process. He has no affiliation to any particular realm of magic, which certainly hinders his ability to employ a formidable legion. For this reason, %1 has had to move in a direction uncommon to most wizards.\
\n\t%1 has adopted a strategy that is extremely effective and quite frustrating to his opponents. Knowing that he can not overwhelm other wizards by summoning creatures, %1 has shifted his attention to widespread movement and land defense. %1 maximizes land acquisition through expert play. In addition, %1 employs the teleport spell to quickly shift his minions for hit and run attacks on lands which have been left penetrable by unsuspecting adversaries. The nature of his magic allows him the luxury of not having to divide his attention between tactical movement and gameplay. %1 can then concentrate his efforts on burying his opponents through advanced rune battle strategy. The Maitha adore his approach, as they are quite passive and profoundly intellectual. They have relied on %1 for many years and continue to have confidence in him. %1 has little room for error because his people will not tolerate failure. Impulsive by nature, the Maitha will not hesitate to dissolve their pact with %1 if he wavers from total success.\
\n\t%1 enjoys the pressures of being Maitha. They think very highly of their race and pride themselves on quick thinking and troubleshooting. It has become a common sight to see %1 dazzling his opponents with brilliant play and decision making, almost toying with them. %1 carries himself with a cocky swagger, knowing that his play has rarely been matched in the past. He very much looks forward to the coming Rune War so he can once again teach the veterans a lesson and embarrass any new comers to the event."),
_("%1's affiliation to a clan is torn due to his lack of a true birthright. He is born of native persuasion, however, he shares the blood of two races. %1's mother was a Maithan Elder and his father was a dedicated Karthan Crusader, making %1 the offspring of two high ranking individuals of conflicting races. While %1 received the favor of both races, sharp Maithan intellect and intense Karthan dedication, he became a source of great conflict. He was an incredible specimen, bred for wizardry and participation in coming Rune Wars. The leaders of each of his clans recognized this and as a result began vying for control of him. %1 left his home, a neutral township between the two clan regions, to seek peace and to concentrate on summoning and enchantment. By putting distance between himself and the clans, %1 forced the leaders to take action in hopes of resolving this issue. It was thought by each clan that if he were to have only one living parent then %1 would become partisan to the clan of the survivor. The Maithans and Karthans agreed to pit the two against each other in a mock Rune War, with the loser to be put to death.. %1, still away in training, did not learn of this event and continued his studies. His mother and father decided it their way. They poisoned themselves and ended this horrible conflict in tragedy. To this day it has been kept secret to %1 and the two nations have resolved to fairly commission %1 when the Rune War comes.\
\n\t%1's magical aura was shaped when he left his home. He sought refuge in the mountains where he became one with the crisp mountain air. He dipped into the magic of the air and learned to harness and control the wonders contained within it. Therefore, without knowledge of a distinct realm, all his summonings are related to flight and the winds. %1 became the self taught master of the air, able to call upon such mystical beings as the Ki-Lin, Griffon, and Air Elemental. His supplemental magic was shaped from a genetic trait given to him by his father. The Karthan dedication to the sword was strong within him so %1 focused on it, allowing it to bubble within him, creating the substance for his enchantments.\
\n\tIt is not known as to which clan %1 will be representing in the coming Rune War. His ignorance towards the fate of his parents protects his relationship with his two native clans. Until %1 discovers the truth he will remain loyal to these clans, having to decide which one he will unite with. If %1 is to learn of the demise of his parents, no one knows what will come of the rage that will boil inside him."),
// towns
_("Tower of 4 Winds"),
_("Maithaius"),
_("Baliphon"),
_("Vermille"),
_("Sulanthia"),
_("Trojensek"),
_("Talon"),
_("Siramak"),
_("Ronzinol"),
_("Corzen"),
_("Greenbaw"),
_("Zubrus"),
_("Corimar"),
_("Inkartha"),
_("Hexan"),
_("Firland"),
_("Vesna"),
_("Kern"),
_("Regency Peaks"),
_("Knighthaven"),
_("Rikter"),
_("Gorok"),
_("Suntura"),
_("Bertram"),
_("Mastenbroek"),
_("Reisse"),
_("Cirrus"),
_("Grosek"),
_("Chahrr"),
_("Saugrezz"),
_("Mahnjeet"),
_("Trassk"),
_("Bechnarr"),
_("Azuria"),
_("Pyramus Reach"),
_("Serenity Plains"),
_("Sunspot"),
_("Charmers Expanse"),
_("Gambit's Run"),
_("Ash Point"),
_("Orchid Bay"),
_("Mocklebury"),
_("Celestial Wood"),
_("Tortoise Isle"),
_("Siphon's Chute"),
// specialization descriptions
_("Creatures employing the ability to swarm may attack a full party instead of just the leader, overwhelming them with sheer numbers."),
_("This ability allows creatures of the same type to link together in battle, instilling a +1 melee and +1 defense to each of these creatures, instead of just the +1 melee usually granted for supporting creatures."),
_("Invisible creatures may move across the isle free from detection, only to appear in combat. Surprise!"),
_("Regenerating creatures are restored to maximum loyalty at the beginning of the map phase."),
_("The presence of the possessor of this ability sends even the bravest of souls into panic. This is reflected by the loss of 2 loyalty points to all that combat it."),
_("Those possessing Major Magic Resistence receive a %%{percent} chance to ignore the effects of spells directed at them by any wizard."),
_("This fearsome ability gives the possessor a %25 chance to strike a devastating blow in combat. A succesful mighty blow boosts melee strength by 3, and guarantees that at least one damage is done, regardless of the opponents defense rating."),
_("This ability allows the unit to teleport into any friendly territory containing a summoning circle by calling on the portals of travel."),
_("Those who possess this ability and lead their party into combat forego ranged combat, and are granted first strike in melee combat. This only applies to attacking parties."),
_("Those blessed with this ability can see invisible units in adjacent territories."),
_("Creatures with this ability can avoid the effects of missile fire when in combat."),
_("Shannahan heals 2 loyalty before movement phase."),
_("The fire shield reduces the loyalty of any creature that strikes its bearer in melee combat by one."),
// creature descriptions
_("\tFoot soldiers of the skull summoning chain, the skeleton horde provides support. Their sheer numbers allow them to swarm, attacking every member of an opposing army."),
_("\tShadows are a useful staple in the skull realm. Their ability to merge amongst themselves and maintain invisibility greatly enhances their attacking prowess."),
_("\tA valued member of the skull summoning realm, the Durlock provides an initial foundation for a strong force with its missile fire and robust attack."),
_("\tWraiths provide the most bang for the buck in the skull regime. Regeneration supplies durability in combat allowing the wraith to clean up any low to mid-range enemies and territories."),
_("\tThe Knight Templar is a solid low range summoning. He has the ability to combat any low to mid-range opponent with his impressive mighty blow."),
_("\tExtremely resilient, the minotaur is an excellent choice for summoners. It possesses solid battle attributes at a reasonable cost."),
_("\tThe adventure party is a wise magical investment. It combines a formidable ground and air assault with a stalwart defense. Its ability to see the invisible can foil enemy plans."),
_("\tThis high range creature is strong in all facets of combat like most sword creatures. Its initial ranged strike is followed by a potent melee attack."),
_("\tThe sand wraith is an exceptional strategic unit because of its invisibility. Pair off a sand wraith or two with a mid range creature and watch the overconfident big ones fall."),
_("\tWith its exceptional resilience and regeneration, the stone golem makes for a solid low range creature ideal for support."),
_("\tThe thunder bird introduces a ranged attack to the number realm. Couple this with hearty melee and loyalty values and you have a powerful mid-range unit."),
_("\tThis fearsome serpent like beast has no visible weaknesses. Its lack of a ranged attack is offset by its ability to ignore missiles while its other abilities are very impressive."),
_("\tA wizard must draw upon the power of the winds to summon a tornado. Astronge mid-ranged being, the tornado offers immunity to missile attacks and consistent battle attributes."),
_("\tThe griffon is a credible strategic unit. Its ability to merge and see the invisible along with its capable combat properties makes it a useful low range creature. An excellent scout with its high movement."),
_("\tChameleons are stealthy archers of the lizard persuasion. Their hearty nature and loyalty to Ziag allow them to recuperate quickly. This is the only invisible unit with ranged attack capability."),
_("\tThe invisible undead knight is a formidable adversary to any mid-range unit. With the addition of supplemental enchantments, Kilor becomes a potent foe to any opponent."),
_("\tThe Demon Lord known as Maz'Ra may well be the most fearsome creature available to summoners. It can single handedly dispatch many capable armies with its overwhelming attack strength and intimidating Hellblast ability."),
_("\tCarol is a versatile addition to any summoner that can call her to battle. Her pendant allows her to gate to friendly summoning circles and gives her army first strike if she leads them into battle by using the short range displacement ability of her pendant."),
_("\tKing Drago is the jewel of the realm of swords. His consistencies in the art of war are bolstered by his resistance to magic. Add his mastery of the fearsome mighty blow and you have an awesome fighting machine. Unfortunately he is difficult to heal."),
_("\tA hauntingly gorgeous individual, Learra's hypnotic song freezes opponents in combat when she leads an attacking party, providing her with the first strike. A good melee property makes this strike quite nasty."),
_("\tShanahan the Cloud Giant is the pinnacle of the number realm. There are many options available to the commander of this big boy. Overwhelm most anything by itself, or attach it to a party and wreak havoc across the Isle."),
_("\tThe White Dragon is extremely resilient and loyal by nature. Factor in its ability to allow the summoner to draw a character rune and its consistent battle characteristics and you have a top notch unit at your command."),
_("\tThe Green Dragon is a very hostile and aggressive beast. Its lack of a missile strike is supplemented by a fearsome attack strength and a high loyalty. When in play, this Dragon grants its controller the ability to draw a sword rune."),
_("\tThe Red Dragon has a particular affinity to the skull realm, allowing its summoner the ability to draw a rune of skulls. It has an intense ranged breath attack and a capable defense making it another powerful minion to do your bidding."),
_("\tThe Fire Elemental is a particularly volatile creature. A potent attack force that employs a solid melee and ranged attack, its ability to grant the random discard spell is its real burn."),
_("\tBorn from the ground beneath, the Earth Elemental is another consistent battle force. The one who controls it receives the ability to peek at his or her opponents hands with the scry runes spell."),
_("\tThe Air Elemental proves to be the greatest combatant af all the elements. Summoners calling upon this element gain the favor of the silence spell, an annoyance to all wizards who are stricken with it."),
_("\tThe Water Elemental is a powerful force on the Isle, and in the Rune Game. Fog is the strategic annoyance granted to the commander of this element."),
_("\tThis creature leads its category on the battlefield. It combines strength, resilience, and broad movement. The Juggernaut is indeed a powerful summons."),
// spell descriptions
_("\tA cloud of billowing smoke surrounds one enemy creature limiting its visibility. This will reduce or negate the target's ability to make a ranged attack."),
_("\tThe caster draws upon the power of the demons to bolster the loyalty of one of his minions."),
_("\tThe summoner directs the face of fear at an enemy army group, sending them into panic and reducing their loyalty."),
_("\tAnother mind altering spell, paralyzing fear ceases the movement of one enemy creature for one turn as it becomes wracked with terror."),
_("\tWith this spell the summoner is able to harness the power of the skull realm to drain the will of one enemy creature, reducing its combat characteristics."),
_("\tAn intense bloodlust flows through the veins of the recipient of this spell, making it a more fierce attacker."),
_("\tThis spell sharpens the vision of one friendly creature with ranged combat ability, enabling it to pinpoint its ranged attack."),
_("\tThe caster of this spell is able to conjure a shield of energy around a single friendly creature, reducing the effectiveness of missile and territory fire against it."),
_("\tSwirling winds surround the target of this spell kicking up dust and other debris. The target becomes distracted and unable to fully defend itself."),
_("\tThe target of this spell becomes inspired by visions of mighty warriors cutting down their enemies. This greatly enhances the combat ability of the enchanted."),
_("\tThe waters of a great mystical fountain are sprinkled upon the recipient of this spell giving it a random bonus. The target receives +Melee, +Loyalty or +Ranged."),
_("\tWhen a friendly creature is enchanted with this spell it becomes extremely eager for battle, sacrificing loyalty for the lust of battle."),
_("\tExtremely bright lights appear and dance around the target of this spell, distracting it from battle and reducing its ability to defend itself."),
_("\tThe magic of this enchantment consumes its target, making it feel more confident in its abilities. As a result, the creature touched by this gains in defense."),
_("\tAn excellent utility spell, teleport allows the caster to call upon the gates of travel to shift any one of his or her minions to any friendly territory."),
_("\tRemoves all enchantments from the target creature. Does not affect any special abilities."),
_("\tThe caster of this spell summons the power of the skies to strike an enemy creature with a lightning bolt. Shocking!"),
_("\tAn important supplementary spell, healing restores two loyalty to a friendly unit. Loyalty will be added up to the target's maximum."),
_("\tThe most destructive spell in the lands, hellblast surrounds a targeted enemy army with a searing hot firestorm causing some major damage."),
// mahjong summary part
_("Land Claims"),
_("Spell Points"),
_("Win Rune"),
_("Sets:"),
_("Points:"),
_("Doubles:"),
// battle summary part
_("Combat"),
_("Summary"),
_("Winner is"),
// game sumary part
_("Category"),
_("Score"),
_("Rank"),
_("Score"),
_("Territory Score"),
_("Summon Circle Score"),
_("Unit Score"),
_("Spell Point Score"),
_("Land Claim Score"),
_("Total Score")
};
#endif
